[project]
name = "bsort"
version = "0.1.0"
description = "Bottle Cap Color Detection CLI and ML Pipeline"
authors = [{ name = "Fadil Farhan Ridwan", email = "fadilfarhan24.ff@email.com" }]
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "ultralytics",
    "click",
    "pyyaml",
    "wandb",
]

[project.scripts]
bsort = "bsort.cli:cli"

[tool.black]
line-length = 88
target-version = ["py310"]

[tool.isort]
profile = "black"

[tool.pylint.'MAIN']
max-line-length = 88
disable = [
    "C0114",
    "C0115",
    "C0116",
]

[tool.pytest.ini_options]
pythonpath = ["."]
addopts = "-q"

# ✅ Tambahan wajib untuk build pip
[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"
